### ISSUE TITLE
ISP Metrics only pulls a timestamp and has no attributes

### ISSUE THREAD

**Issue by tuckshoprn** [biofects/HA-UniFi-Site-Manager#2]
I have a UDM SE, and other unifi equipment.  This integration works perfectly as per the readme, except for the ISP metrics.  It only pulls a timestamp, but the attributes dont exist.  According to the readme, it should have:

    State: Current timestamp _- this is correctly pulled_
    Attributes: _- no attributes are present_
        Latency metrics (avg, min, max)
        Packet loss (percentage, count)
        Bandwidth (download/upload Mbps)
        WAN metrics:
            Latency (avg, max)
            Bandwidth (download/upload kbps)
            Packet loss
            Uptime/downtime
            ISP details (name, ASN)

Is there something further I need to do to get the attributes to come through?  I have read through the readme and followed it, I have looked into the sensor.py script, but I am not very good at python, and didnt spot any obvious reason it wouldnt pull the attributes.

**Comment by biofects** [comment]
Thank you for the report. I see my ISP only has timestamp as well. Let me dig into this.

**Comment by biofects** [comment]
Please test v1.0.0 this helped me make it final. I think isp metrics are fixed

**Comment by tuckshoprn** [comment]
Ia there a way to pull the speedtest results from unifi dashboard?  I found the api call that the dashboard makes, but have been unable to successfully get a rest sensor to login and pull the json.  I wonder if it is exposed on this api also?
for anyone interseted the api address to get the json for the dashboard is:
`/proxy/network/v2/api/site/default/aggregated-dashboard?historySeconds=86400`

**Comment by biofects** [comment]
Let me investigate all the responses and see if there is an easy way

**Comment by biofects** [comment]
Ok from this plugin it is not available yet from the site manager api. I did send a request for more data to be pulled but at mercy of large tech :) 
However, I could possibly create a simple plugin that connects to your controller locally (or if available public) and pull speed test results.

**Comment by tuckshoprn** [comment]
That would be brilliant, I have tried to create a rest sensor that sends the login form and then grabs the json, but I must be doing something wrong as it keeps telling me "405 method not allowed"
The speed test results are really the only thing that I need that is still missing from unifi's api.
Thank you.

**Comment by biofects** [comment]
OK its going to be tricky, i really do not like doing user/pass auth, but can be done. I'm looking through snmp data to see if I can find an OID, unfortunately not all the snmp's have labels :(

**Comment by tuckshoprn** [comment]
I also looked through the snmp OID, but was unable to locate the speedtest results.  The only place I can find them is on the https api call from the dashboard.  It needs to authenticate to https://unifi.address/api/auth/login by posting a json format of {'username': 'username', 'password': 'supersecretpassword', 'token': '', 'rememberMe': 'false'}. This then returns a token cookie and an X-CSRF-Token, and an updated-X-CSRF-Token in the response header.  To get to the dashboard resource requires the headers sent to include the updated-x-csrf-token and the cookie, in order for it to repond.  I just cant seem to find a way to dynamically grab those values and include them in the request header.  I was trying it using multiscrape sensor, and also the restful sensor on HA, but despite reading tons of documentation, i'm still at a loss.  I've probably missed something obvious.
I also do not like using user/pass authentication, however i cannot seem to find another way to grab this info at the moment.

**Comment by biofects** [comment]
Yes, that is probably the route I will take. I will try to have a HA plugin in a couple days.

**Comment by biofects** [comment]
Before I write the plugin, please note https://www.home-assistant.io/integrations/unifi/ does give a ton of information for your udm, including speed test. If you want just a speed test results plugin I can still write one.

**Comment by tuckshoprn** [comment]
I do use that plugin, but have never been able to get the Speedtest results from it. Perhaps I am missing them in the configuration, I will have another look. Thank you for your help.

**Comment by tuckshoprn** [comment]
I left a comment for the owner of the Aiounifi GitHub to see if the Speedtest results can be pulled using that plugin. Like you say, it seems to have all the other data. Thank you for your time.

**Comment by biofects** [comment]
I can still make the plugin if you want.

**Comment by tuckshoprn** [comment]
If you can make one, that would be fantastic, I cant seem to get the multiscrape or rest sensor to play ball.  A standalone plugin to get the speedtest info would be great.  Happy to help with testing it.

**Comment by biofects** [comment]
Ok ill start working on one this weekend

**Comment by biofects** [comment]
I think I have a very simple speed test plugin. I will publish it today and you can test for me

**Comment by biofects** [comment]
Ok release is done https://github.com/biofects/HA-Unifi-Speedtest/ Ill close this out and we can work on any issues on the new plugin

**Comment by tuckshoprn** [comment]
Thankyou, due to storms at home, my fibre has been severed by a tree! So I'll test when I can, hopefully it'll be up and running by start of next week.
